services:
  mysql:
    image: mysql:8.0
    container_name: mysql_loja
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loja_desportiva
    ports:
      - "3306:3306"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_general_ci"
    ]
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
